[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Arsip"
  url = "arsip"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "Gallery"
  url = "gallery"
  weight = 3
    
[[main]]
  parent = "gallery"
  name = "Cartoon"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "Photo"
  url = "gallery/photo"

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 5
  
  [[main]]
  identifier = "Topik"
  name = "topik"
  url = ""
  weight = 6

